- name: configuring frontend
  hosts: frontend
  vars:

  tasks:
  - name: installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed
  
  - name: enable and start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true

  - name: remove files
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent

  - name: frontend download
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /usr/share/nginx/html

  - name: copying expense conf file
    ansible.builtin.copy:
      src: /home/ec2-user/05-expense-ansible/expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted